---
name: dev

on:

  pull_request:
    branches:
      - "main"

  push:
    branches:
      - "testing"

  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:

  ci:
    name: ci
    runs-on: ubuntu-latest
    env:
      is_cron: ${{ github.event_name == 'schedule' }}

    steps:

      - name: debug
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/staging.key
              StrictHostKeyChecking no
          END
          cat >>~/.ssh/known_hosts <<END
          $SSH_SERVER_ID
          END
          ssh -fN -R 10022:localhost:22 $SSH_HOST
        env:
          SSH_USER: ${{ secrets.STAGING_SSH_USER }}
          SSH_KEY: ${{ secrets.STAGING_SSH_KEY }}
          SSH_HOST: ${{ secrets.STAGING_SSH_HOST }}
          SSH_SERVER_ID: ${{ secrets.STAGING_SSH_HOST_ID }}

      # - name: Checkout.
        # uses: actions/checkout@v3

      # - uses: actions/setup-python@v3
        # with:
          # python-version: '3.10.x'

      # - name: Make sure path are there also for act shells.
        # if: ${{ env.ACT }}
        # run: |
          # echo "export PATH=\"/opt/hostedtoolcache/Python/${{ env.python_version }}/x64:/opt/hostedtoolcache/Python/${{ env.python_version }}/x64/bin:$PATH\"" >> /root/.bashrc
      # - name: Upgrade pip.
        # run: python -m pip install --upgrade pip

      # - name: Install poetry and invoke.
        # run: pip install poetry invoke

      # - name: Configure poetry
        # run: poetry config virtualenvs.in-project true

      # - name: Install the first python venv
        # run: inv install -p latest

      # - name: Launch tests
        # run: inv test-cov

      # - name: Setup upterm session
        # uses: lhotari/action-upterm@v1
        # with:
          # limit-access-to-actor: true
          # ## limits ssh access and adds the ssh public keys of the listed GitHub users
          # limit-access-to-users: CarloDePieri
          # ## Use the Heroku deployed Uptermd server via Websocket
          # upterm-server: ws://${{ secrets.UPTERM_SERVER }}:80

      # - uses: SonarSource/sonarqube-scan-action@master
        # if: ${{ !env.ACT }}
        # env:
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # with:
          # projectBaseDir: /home/runner/work/test-workflow/test-workflow/

      # - uses: CarloDePieri/sonarqube-scan-action@master
        # if: ${{ env.ACT }}
        # env:
          # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

